1. Load Dataset
2. eng-> sentence ko  convert -> Embedding mein
 *  tokenization for unique word
3. Build RNN
4. Train
5. Prediction

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('100_Unique_QA_Dataset.csv')

In [ ]:
df.shape

(90, 2)

In [ ]:
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [ ]:
# Tokenize
def tokenize(text):
    text= text.lower()
    text= text.replace('.','')
    text= text.replace(',','')
    text= text.replace('?','')
    text= text.replace('!','')
    return text.split()

In [ ]:
tokenize('What is the capital of France?')

['what', 'is', 'the', 'capital', 'of', 'france']

In [ ]:
# Vocab To gather unique word
vocab={'<UNK>':0}

In [ ]:
def build_vocab(row):
   tokenized_question= tokenize(row['question'])
   tokenized_answer= tokenize(row['answer'])

   merged_tokens= tokenized_question + tokenized_answer

   for token in merged_tokens:
      if token not in vocab:
         vocab[token]= len(vocab)
   print(tokenized_question,tokenized_answer)

In [ ]:
df.apply(build_vocab,axis=1)

['what', 'is', 'the', 'capital', 'of', 'france'] ['paris']
['what', 'is', 'the', 'capital', 'of', 'germany'] ['berlin']
['who', 'wrote', "'to", 'kill', 'a', "mockingbird'"] ['harper-lee']
['what', 'is', 'the', 'largest', 'planet', 'in', 'our', 'solar', 'system'] ['jupiter']
['what', 'is', 'the', 'boiling', 'point', 'of', 'water', 'in', 'celsius'] ['100']
['who', 'painted', 'the', 'mona', 'lisa'] ['leonardo-da-vinci']
['what', 'is', 'the', 'square', 'root', 'of', '64'] ['8']
['what', 'is', 'the', 'chemical', 'symbol', 'for', 'gold'] ['au']
['which', 'year', 'did', 'world', 'war', 'ii', 'end'] ['1945']
['what', 'is', 'the', 'longest', 'river', 'in', 'the', 'world'] ['nile']
['what', 'is', 'the', 'capital', 'of', 'japan'] ['tokyo']
['who', 'developed', 'the', 'theory', 'of', 'relativity'] ['albert-einstein']
['what', 'is', 'the', 'freezing', 'point', 'of', 'water', 'in', 'fahrenheit'] ['32']
['which', 'planet', 'is', 'known', 'as', 'the', 'red', 'planet'] ['mars']
['who', 'is', 'the', 'author', 'of', "'1984'"] ['george-orwell']
['what', 'is', 'the', 'currency', 'of', 'the', 'united', 'kingdom'] ['pound']
['what', 'is', 'the', 'capital', 'of', 'india'] ['delhi']
['who', 'discovered', 'gravity'] ['newton']
['how', 'many', 'continents', 'are', 'there', 'on', 'earth'] ['7']
['which', 'gas', 'do', 'plants', 'use', 'for', 'photosynthesis'] ['co2']
['what', 'is', 'the', 'smallest', 'prime', 'number'] ['2']
['who', 'invented', 'the', 'telephone'] ['alexander-graham-bell']
['what', 'is', 'the', 'capital', 'of', 'australia'] ['canberra']
['which', 'ocean', 'is', 'the', 'largest'] ['pacific-ocean']
['what', 'is', 'the', 'speed', 'of', 'light', 'in', 'vacuum'] ['299792458m/s']
['which', 'language', 'is', 'spoken', 'in', 'brazil'] ['portuguese']
['who', 'discovered', 'penicillin'] ['alexander-fleming']
['what', 'is', 'the', 'capital', 'of', 'canada'] ['ottawa']
['what', 'is', 'the', 'largest', 'mammal', 'on', 'earth'] ['whale']
['which', 'element', 'has', 'the', 'atomic', 'number', '1'] ['hydrogen']
['what', 'is', 'the', 'tallest', 'mountain', 'in', 'the', 'world'] ['everest']
['which', 'city', 'is', 'known', 'as', 'the', 'big', 'apple'] ['newyork']
['how', 'many', 'planets', 'are', 'in', 'the', 'solar', 'system'] ['8']
['who', 'painted', "'starry", "night'"] ['vangogh']
['what', 'is', 'the', 'chemical', 'formula', 'of', 'water'] ['h2o']
['what', 'is', 'the', 'capital', 'of', 'italy'] ['rome']
['which', 'country', 'is', 'famous', 'for', 'sushi'] ['japan']
['who', 'was', 'the', 'first', 'person', 'to', 'step', 'on', 'the', 'moon'] ['armstrong']
['what', 'is', 'the', 'main', 'ingredient', 'in', 'guacamole'] ['avocado']
['how', 'many', 'sides', 'does', 'a', 'hexagon', 'have'] ['6']
['what', 'is', 'the', 'currency', 'of', 'china'] ['yuan']
['who', 'wrote', "'pride", 'and', "prejudice'"] ['jane-austen']
['what', 'is', 'the', 'chemical', 'symbol', 'for', 'iron'] ['fe']
['what', 'is', 'the', 'hardest', 'natural', 'substance', 'on', 'earth'] ['diamond']
['which', 'continent', 'is', 'the', 'largest', 'by', 'area'] ['asia']
['who', 'was', 'the', 'first', 'president', 'of', 'the', 'united', 'states'] ['george-washington']
['which', 'bird', 'is', 'known', 'for', 'its', 'ability', 'to', 'mimic', 'sounds'] ['parrot']
['what', 'is', 'the', 'longest-running', 'animated', 'tv', 'show'] ['simpsons']
['what', 'is', 'the', 'smallest', 'country', 'in', 'the', 'world'] ['vaticancity']
['which', 'planet', 'has', 'the', 'most', 'moons'] ['saturn']
['who', 'wrote', "'romeo", 'and', "juliet'"] ['shakespeare']
['what', 'is', 'the', 'main', 'gas', 'in', "earth's", 'atmosphere'] ['nitrogen']
['how', 'many', 'bones', 'are', 'in', 'the', 'adult', 'human', 'body'] ['206']
['which', 'metal', 'is', 'a', 'liquid', 'at', 'room', 'temperature'] ['mercury']
['what', 'is', 'the', 'capital', 'of', 'russia'] ['moscow']
['who', 'discovered', 'electricity'] ['benjamin-franklin']
['which', 'is', 'the', 'second-largest', 'country', 'by', 'land', 'area'] ['canada']
['what', 'is', 'the', 'color', 'of', 'a', 'ripe', 'banana'] ['yellow']
['which', 'month', 'has', '28', 'days', 'in', 'a', 'common', 'year'] ['february']
['what', 'is', 'the', 'study', 'of', 'living', 'organisms', 'called'] ['biology']
['which', 'country', 'is', 'home', 'to', 'the', 'great', 'wall'] ['china']
['what', 'do', 'bees', 'collect', 'from', 'flowers'] ['nectar']
['what', 'is', 'the', 'opposite', 'of', "'day'"] ['night']
['what', 'is', 'the', 'capital', 'of', 'south', 'korea'] ['seoul']
['who', 'invented', 'the', 'light', 'bulb'] ['edison']
['which', 'gas', 'do', 'humans', 'breathe', 'in', 'for', 'survival'] ['oxygen']
['what', 'is', 'the', 'square', 'root', 'of', '144'] ['12']
['which', 'country', 'has', 'the', 'pyramids', 'of', 'giza'] ['egypt']
['which', 'sea', 'creature', 'has', 'eight', 'arms'] ['octopus']
['which', 'holiday', 'is', 'celebrated', 'on', 'december', '25'] ['christmas']
['what', 'is', 'the', 'currency', 'of', 'japan'] ['yen']
['how', 'many', 'legs', 'does', 'a', 'spider', 'have'] ['8']
['which', 'sport', 'uses', 'a', 'net', 'ball', 'and', 'hoop'] ['basketball']
['which', 'country', 'is', 'famous', 'for', 'its', 'kangaroos'] ['australia']
['who', 'was', 'the', 'first', 'female', 'prime', 'minister', 'of', 'the', 'uk'] ['margaretthatcher']
['which', 'is', 'the', 'fastest', 'land', 'animal'] ['cheetah']
['what', 'is', 'the', 'first', 'element', 'on', 'the', 'periodic', 'table'] ['hydrogen']
['what', 'is', 'the', 'capital', 'of', 'spain'] ['madrid']
['which', 'planet', 'is', 'the', 'closest', 'to', 'the', 'sun'] ['mercury']
['who', 'is', 'known', 'as', 'the', 'father', 'of', 'computers'] ['charlesbabbage']
['what', 'is', 'the', 'capital', 'of', 'mexico'] ['mexicocity']
['how', 'many', 'colors', 'are', 'in', 'a', 'rainbow'] ['7']
['which', 'musical', 'instrument', 'has', 'black', 'and', 'white', 'keys'] ['piano']
['who', 'discovered', 'the', 'americas', 'in', '1492'] ['christophercolumbus']
['which', 'disney', 'character', 'has', 'a', 'long', 'nose', 'and', 'grows', 'it', 'when', 'lying'] ['pinocchio']
['who', 'directed', 'the', 'movie', "'titanic'"] ['jamescameron']
['which', 'superhero', 'is', 'also', 'known', 'as', 'the', 'dark', 'knight'] ['batman']
['what', 'is', 'the', 'capital', 'of', 'brazil'] ['brasilia']
['which', 'fruit', 'is', 'known', 'as', 'the', 'king', 'of', 'fruits'] ['mango']
['which', 'country', 'is', 'known', 'for', 'the', 'eiffel', 'tower'] ['france']

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [ ]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 "'to": 12,
 'kill': 13,
 'a': 14,
 "mockingbird'": 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 "'1984'": 67,
 'george-orwell': 68,
 'currency': 69,
 'united': 70,
 'kingdom': 71,
 'pound': 72,
 'india': 73,
 'delhi': 74,
 'discovered': 75,
 'gravity': 76,
 'newton': 77,
 'how': 78,
 'many': 79,
 'continents': 80,
 'are': 81,
 'there': 82,
 'on': 83,
 'earth': 84,
 '7': 85,
 'gas': 86,
 'do': 87,
 'plants': 88,
 'use': 89,
 'photosynthesis': 90,
 'co2': 91,
 'smallest': 92,
 'prime': 93,
 'number': 94,
 '2': 95,
 'invented': 96,
 'telephone': 97,
 'alexander-graham-bell': 98,
 'australia': 99,
 'canberra': 100,
 'ocean': 101,
 'pacific-ocean': 102,
 'speed': 103,
 'light': 104,
 'vacuum': 105,
 '299792458m/s': 106,
 'language': 107,
 'spoken': 108,
 'brazil': 109,
 'portuguese': 110,
 'penicillin': 111,
 'alexander-fleming': 112,
 'canada': 113,
 'ottawa': 114,
 'mammal': 115,
 'whale': 116,
 'element': 117,
 'has': 118,
 'atomic': 119,
 '1': 120,
 'hydrogen': 121,
 'tallest': 122,
 'mountain': 123,
 'everest': 124,
 'city': 125,
 'big': 126,
 'apple': 127,
 'newyork': 128,
 'planets': 129,
 "'starry": 130,
 "night'": 131,
 'vangogh': 132,
 'formula': 133,
 'h2o': 134,
 'italy': 135,
 'rome': 136,
 'country': 137,
 'famous': 138,
 'sushi': 139,
 'was': 140,
 'first': 141,
 'person': 142,
 'to': 143,
 'step': 144,
 'moon': 145,
 'armstrong': 146,
 'main': 147,
 'ingredient': 148,
 'guacamole': 149,
 'avocado': 150,
 'sides': 151,
 'does': 152,
 'hexagon': 153,
 'have': 154,
 '6': 155,
 'china': 156,
 'yuan': 157,
 "'pride": 158,
 'and': 159,
 "prejudice'": 160,
 'jane-austen': 161,
 'iron': 162,
 'fe': 163,
 'hardest': 164,
 'natural': 165,
 'substance': 166,
 'diamond': 167,
 'continent': 168,
 'by': 169,
 'area': 170,
 'asia': 171,
 'president': 172,
 'states': 173,
 'george-washington': 174,
 'bird': 175,
 'its': 176,
 'ability': 177,
 'mimic': 178,
 'sounds': 179,
 'parrot': 180,
 'longest-running': 181,
 'animated': 182,
 'tv': 183,
 'show': 184,
 'simpsons': 185,
 'vaticancity': 186,
 'most': 187,
 'moons': 188,
 'saturn': 189,
 "'romeo": 190,
 "juliet'": 191,
 'shakespeare': 192,
 "earth's": 193,
 'atmosphere': 194,
 'nitrogen': 195,
 'bones': 196,
 'adult': 197,
 'human': 198,
 'body': 199,
 '206': 200,
 'metal': 201,
 'liquid': 202,
 'at': 203,
 'room': 204,
 'temperature': 205,
 'mercury': 206,
 'russia': 207,
 'moscow': 208,
 'electricity': 209,
 'benjamin-franklin': 210,
 'second-largest': 211,
 'land': 212,
 'color': 213,
 'ripe': 214,
 'banana': 215,
 'yellow': 216,
 'month': 217,
 '28': 218,
 'days': 219,
 'common': 220,
 'february': 221,
 'study': 222,
 'living': 223,
 'organisms': 224,
 'called': 225,
 'biology': 226,
 'home': 227,
 'great': 228,
 'wall': 229,
 'bees': 230,
 'collect': 231,
 'from': 232,
 'flowers': 233,
 'nectar': 234,
 'opposite': 235,
 "'day'": 236,
 'night': 237,
 'south': 238,
 'korea': 239,
 'seoul': 240,
 'bulb': 241,
 'edison': 242,
 'humans': 243,
 'breathe': 244,
 'survival': 245,
 'oxygen': 246,
 '144': 247,
 '12': 248,
 'pyramids': 249,
 'giza': 250,
 'egypt': 251,
 'sea': 252,
 'creature': 253,
 'eight': 254,
 'arms': 255,
 'octopus': 256,
 'holiday': 257,
 'celebrated': 258,
 'december': 259,
 '25': 260,
 'christmas': 261,
 'yen': 262,
 'legs': 263,
 'spider': 264,
 'sport': 265,
 'uses': 266,
 'net': 267,
 'ball': 268,
 'hoop': 269,
 'basketball': 270,
 'kangaroos': 271,
 'female': 272,
 'minister': 273,
 'uk': 274,
 'margaretthatcher': 275,
 'fastest': 276,
 'animal': 277,
 'cheetah': 278,
 'periodic': 279,
 'table': 280,
 'spain': 281,
 'madrid': 282,
 'closest': 283,
 'sun': 284,
 'father': 285,
 'computers': 286,
 'charlesbabbage': 287,
 'mexico': 288,
 'mexicocity': 289,
 'colors': 290,
 'rainbow': 291,
 'musical': 292,
 'instrument': 293,
 'black': 294,
 'white': 295,
 'keys': 296,
 'piano': 297,
 'americas': 298,
 '1492': 299,
 'christophercolumbus': 300,
 'disney': 301,
 'character': 302,
 'long': 303,
 'nose': 304,
 'grows': 305,
 'it': 306,
 'when': 307,
 'lying': 308,
 'pinocchio': 309,
 'directed': 310,
 'movie': 311,
 "'titanic'": 312,
 'jamescameron': 313,
 'superhero': 314,
 'also': 315,
 'dark': 316,
 'knight': 317,
 'batman': 318,
 'brasilia': 319,
 'fruit': 320,
 'king': 321,
 'fruits': 322,
 'mango': 323,
 'eiffel': 324,
 'tower': 325}

In [ ]:
len(vocab)

326

In [ ]:
# Conveet into numerical index
def text_to_indices(text, vocab):
  indexed_text=[]
  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])
  return indexed_text

In [ ]:
text_to_indices("What is the capital of prince?",vocab)

[1, 2, 3, 4, 5, 0]

In [ ]:
import torch
from torch.utils.data import Dataset,DataLoader

In [ ]:
class QADataset(Dataset):
  def  __init__(self, df,vocab):
    self.df= df
    self.vocab=vocab
  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self, index):
    numerical_question= text_to_indices(self.df.iloc[index]['question'],self.vocab)
    numerical_answer= text_to_indices(self.df.iloc[index]['answer'],self.vocab)

    return torch.tensor(numerical_question),torch.tensor(numerical_answer)

In [ ]:
dataset= QADataset(df,vocab)

In [ ]:
dataset[9]

(tensor([ 1,  2,  3, 50, 51, 19,  3, 45]), tensor([52]))

In [ ]:
dataloader= DataLoader(dataset,batch_size=1,shuffle=True)

In [ ]:
for question,answer in dataloader:
  print(question)
  print(answer)

tensor([[ 42, 137, 118,   3, 249,   5, 250]])
tensor([[251]])
tensor([[ 42,  18, 118,   3, 187, 188]])
tensor([[189]])
tensor([[10, 75, 76]])
tensor([[77]])
tensor([[  1,   2,   3, 181, 182, 183, 184]])
tensor([[185]])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]])
tensor([[106]])
tensor([[ 10, 140,   3, 141, 142, 143, 144,  83,   3, 145]])
tensor([[146]])
tensor([[ 42, 201,   2,  14, 202, 203, 204, 205]])
tensor([[206]])
tensor([[ 42, 137,   2, 227, 143,   3, 228, 229]])
tensor([[156]])
tensor([[  1,   2,   3, 213,   5,  14, 214, 215]])
tensor([[216]])
tensor([[  1,   2,   3,   4,   5, 288]])
tensor([[289]])
tensor([[ 42, 168,   2,   3,  17, 169, 170]])
tensor([[171]])
tensor([[ 10, 140,   3, 141, 272,  93, 273,   5,   3, 274]])
tensor([[275]])
tensor([[  1,   2,   3,   4,   5, 281]])
tensor([[282]])
tensor([[ 42, 320,   2,  62,  63,   3, 321,   5, 322]])
tensor([[323]])
tensor([[ 78,  79, 263, 152,  14, 264, 154]])
tensor([[36]])
tensor([[ 1,  2,  3, 92, 93, 94]])
tensor([[95]])
tensor([[ 42, 292, 293, 118, 294, 159, 295, 296]])
tensor([[297]])
tensor([[  1,   2,   3,   4,   5, 113]])
tensor([[114]])
tensor([[ 10,  29, 130, 131]])
tensor([[132]])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]])
tensor([[61]])
tensor([[10,  2,  3, 66,  5, 67]])
tensor([[68]])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]])
tensor([[23]])
tensor([[ 42, 314,   2, 315,  62,  63,   3, 316, 317]])
tensor([[318]])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]])
tensor([[128]])
tensor([[ 78,  79, 290,  81,  19,  14, 291]])
tensor([[85]])
tensor([[  1,   2,   3, 147,  86,  19, 193, 194]])
tensor([[195]])
tensor([[  1,   2,   3, 235,   5, 236]])
tensor([[237]])
tensor([[  1,   2,   3, 164, 165, 166,  83,  84]])
tensor([[167]])
tensor([[ 10,  75,   3, 298,  19, 299]])
tensor([[300]])
tensor([[10, 96,  3, 97]])
tensor([[98]])
tensor([[ 10,  11, 158, 159, 160]])
tensor([[161]])
tensor([[ 10,  11, 190, 159, 191]])
tensor([[192]])
tensor([[ 1,  2,  3, 33, 34,  5, 35]])
tensor([[36]])
tensor([[ 1,  2,  3,  4,  5, 73]])
tensor([[74]])
tensor([[ 42,   2,   3, 211, 137, 169, 212, 170]])
tensor([[113]])
tensor([[  1,   2,   3,   4,   5, 109]])
tensor([[319]])
tensor([[ 42, 257,   2, 258,  83, 259, 260]])
tensor([[261]])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]])
tensor([[28]])
tensor([[78, 79, 80, 81, 82, 83, 84]])
tensor([[85]])
tensor([[  1,   2,   3, 222,   5, 223, 224, 225]])
tensor([[226]])
tensor([[ 42, 137,   2, 138,  39, 139]])
tensor([[53]])
tensor([[ 42, 175,   2,  62,  39, 176, 177, 143, 178, 179]])
tensor([[180]])
tensor([[10, 11, 12, 13, 14, 15]])
tensor([[16]])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]])
tensor([[186]])
tensor([[ 10, 310,   3, 311, 312]])
tensor([[313]])
tensor([[ 10,  75, 111]])
tensor([[112]])
tensor([[ 42, 217, 118, 218, 219,  19,  14, 220,  43]])
tensor([[221]])
tensor([[10, 55,  3, 56,  5, 57]])
tensor([[58]])
tensor([[  1,   2,   3,  33,  34,   5, 247]])
tensor([[248]])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]])
tensor([[52]])
tensor([[ 42, 101,   2,   3,  17]])
tensor([[102]])
tensor([[ 10,  96,   3, 104, 241]])
tensor([[242]])
tensor([[ 42, 301, 302, 118,  14, 303, 304, 159, 305, 306, 307, 308]])
tensor([[309]])
tensor([[ 42, 117, 118,   3, 119,  94, 120]])
tensor([[121]])
tensor([[  1,   2,   3, 141, 117,  83,   3, 279, 280]])
tensor([[121]])
tensor([[ 1,  2,  3,  4,  5, 99]])
tensor([[100]])
tensor([[  1,   2,   3, 147, 148,  19, 149]])
tensor([[150]])
tensor([[10, 29,  3, 30, 31]])
tensor([[32]])
tensor([[ 10,  75, 209]])
tensor([[210]])
tensor([[  1,  87, 230, 231, 232, 233]])
tensor([[234]])
tensor([[  1,   2,   3,   4,   5, 207]])
tensor([[208]])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]])
tensor([[72]])
tensor([[1, 2, 3, 4, 5, 8]])
tensor([[9]])
tensor([[42, 43, 44, 45, 46, 47, 48]])
tensor([[49]])
tensor([[ 42,  86,  87, 243, 244,  19,  39, 245]])
tensor([[246]])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]])
tensor([[36]])
tensor([[ 78,  79, 151, 152,  14, 153, 154]])
tensor([[155]])
tensor([[ 10, 140,   3, 141, 172,   5,   3,  70, 173]])
tensor([[174]])
tensor([[ 42, 107,   2, 108,  19, 109]])
tensor([[110]])
tensor([[  1,   2,   3,  69,   5, 156]])
tensor([[157]])
tensor([[ 42,  18,   2,   3, 283, 143,   3, 284]])
tensor([[206]])
tensor([[  1,   2,   3,  17, 115,  83,  84]])
tensor([[116]])
tensor([[ 42,   2,   3, 276, 212, 277]])
tensor([[278]])
tensor([[  1,   2,   3,   4,   5, 238, 239]])
tensor([[240]])
tensor([[  1,   2,   3,  37,  38,  39, 162]])
tensor([[163]])
tensor([[ 10,   2,  62,  63,   3, 285,   5, 286]])
tensor([[287]])
tensor([[ 42, 137,   2, 138,  39, 176, 271]])
tensor([[99]])
tensor([[ 1,  2,  3,  4,  5, 53]])
tensor([[54]])
tensor([[ 1,  2,  3, 37, 38, 39, 40]])
tensor([[41]])
tensor([[ 42, 137,   2,  62,  39,   3, 324, 325]])
tensor([[6]])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]])
tensor([[124]])
tensor([[42, 86, 87, 88, 89, 39, 90]])
tensor([[91]])
tensor([[ 78,  79, 196,  81,  19,   3, 197, 198, 199]])
tensor([[200]])
tensor([[  1,   2,   3,  37, 133,   5,  26]])
tensor([[134]])
tensor([[ 1,  2,  3, 69,  5, 53]])
tensor([[262]])
tensor([[ 42, 265, 266,  14, 267, 268, 159, 269]])
tensor([[270]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[ 42, 252, 253, 118, 254, 255]])
tensor([[256]])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]])
tensor([[65]])
tensor([[  1,   2,   3,   4,   5, 135]])
tensor([[136]])

**RNN Architecture**

1 Hiddden layer

embedding layers 50 dimensions nwurons

input :50

hidden node :64

output neurons = total no of unique word= 326

In [ ]:
import torch.nn as nn

In [ ]:
class SimpleRNN(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.embedding= nn.Embedding(vocab_size,50)
    self.rnn= nn.RNN(50,64,batch_first=True)
    self.fc= nn.Linear(64,vocab_size)

  def forward(self,question):
     embedded_question= self.embedding(question)
     hidden,final= self.rnn(embedded_question)
     output= self.fc(final.squeeze(0))
     return output

In [ ]:
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True)
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e = z(d.squeeze(0))

print("shape of e:", e.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])

In [ ]:
dataset[0][0]

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
x= nn.Embedding(326,embedding_dim=50)

In [ ]:
x(dataset[0][0]).shape

torch.Size([6, 50])

In [ ]:
a=x(dataset[0][0])
a

tensor([[ 1.3878, -0.5097,  0.9714,  0.4275,  0.2133,  0.1987, -0.2066, -1.0599,
          0.9745,  0.6019,  0.6312,  1.9109, -1.0838, -2.3717, -0.3271, -0.9745,
         -0.6795,  0.9482, -0.8393,  0.3333, -0.2326,  1.7608,  0.2431,  0.7637,
         -0.2915,  0.7062,  0.8014, -0.7105,  0.7665, -2.1762, -0.1654,  0.0627,
         -0.5568,  0.3721,  0.2441,  0.8657,  0.5548,  1.2261,  0.3596,  1.1864,
         -0.4869, -1.4914, -0.3378, -0.9150,  1.5067, -0.8239,  0.4934,  0.2048,
         -2.2074,  1.0418],
        [-0.3428,  1.8485,  1.9431,  0.8385, -0.4244,  1.6165, -0.1236, -0.1755,
          0.8229, -0.3226, -0.6104,  0.4015, -0.0379,  2.2622,  0.7406, -2.2606,
         -0.2557, -0.5371, -0.7922,  0.2448, -0.0493, -1.7154, -0.5713,  0.3162,
         -0.1998,  0.5611,  0.5044,  2.0306,  0.2209, -0.1869, -1.0481, -1.1075,
          1.5896,  2.1494, -0.2181, -0.6091,  0.8686, -1.3651, -1.2352,  0.0701,
          1.6205,  0.7181, -0.3668, -1.4535,  1.7570,  0.0705,  0.9510, -1.4603,
         -0.4331,  0.3757],
        [-0.5850,  0.5698, -0.1661,  0.2988,  0.8266,  0.9398,  0.8794, -1.2667,
         -2.4024,  0.0464, -1.0073, -2.6391, -1.9564,  0.7320, -0.7697, -0.5382,
          0.0649,  0.9425, -0.1656, -0.0075, -1.0209,  0.9983, -0.3412,  0.3121,
         -0.0319, -0.6678, -1.8540,  0.9251, -0.6844, -1.1288,  0.6994,  0.3790,
         -1.1109,  0.7865,  0.3143, -1.2500,  1.2415, -0.1199, -1.1471, -0.0591,
          0.8202, -1.6824, -1.1859,  0.1921,  0.0355,  0.8033,  1.2965, -0.2605,
         -0.6648,  0.0378],
        [-0.0679, -0.7705,  0.7712, -0.0687,  0.9564,  1.0132,  0.1989,  0.5623,
          0.9694, -0.0031,  0.9157,  2.1720,  0.2337,  1.6519,  0.5187, -0.1479,
         -0.2764,  1.6379, -0.3641,  1.0729, -1.2882,  0.0260,  1.7046, -0.2986,
         -1.9343,  0.9607,  1.3321, -1.2081,  0.2620,  0.8879,  1.8195, -0.9354,
         -0.2070,  0.3730, -1.9656,  0.8288, -0.4460,  0.4869,  0.6194, -1.1279,
          1.0473,  0.6165, -1.4645, -0.0270, -0.2097,  0.1204,  0.4086,  1.0593,
         -0.5960, -1.7481],
        [-0.2760, -0.9253,  0.0610,  0.8327,  1.8996,  1.4842,  0.9891,  1.0525,
         -1.0852, -2.0211,  1.0894, -1.8241, -1.4846, -0.4104,  0.2909,  1.0130,
         -0.8462,  0.4455, -0.3497,  0.5249,  0.5450,  0.7828,  0.9826,  0.8232,
         -0.0882,  0.4185, -0.3213, -1.0725, -0.1787, -0.7476, -0.3478,  0.5463,
          0.2887,  1.5804,  0.8519, -0.2084, -2.2049, -0.1382,  0.0696, -1.8835,
         -0.6487,  1.2686,  0.9522,  0.5538,  0.1983,  0.8960,  1.1135,  0.2672,
         -0.5775,  3.0404],
        [ 2.1109, -1.5801,  0.1703, -0.5942, -0.0410,  0.6147, -0.6939, -0.5171,
         -2.3128,  0.7694,  0.4513,  1.2944,  0.2635,  0.4494,  0.6787,  1.7214,
         -1.8880,  1.2519,  0.2738, -0.0201, -0.0694, -0.0994,  1.3315,  0.0065,
          0.5496, -0.3787,  0.0254,  0.7243,  1.1685, -0.6815,  0.5264,  0.8098,
          0.7081, -0.4692,  0.5968,  0.7162,  0.5165, -0.7658,  0.6178,  0.2310,
         -2.1837, -0.4808, -2.2923, -1.2442,  0.7096,  0.1813, -1.2939, -0.3896,
         -1.9980, -1.4277]], grad_fn=<EmbeddingBackward0>)

In [ ]:
y=nn.RNN(50,64)

In [ ]:
y(a)

(tensor([[ 0.1108,  0.4846,  0.1447, -0.2413, -0.4205, -0.4411,  0.4958,  0.1356,
           0.3548, -0.5753, -0.2816, -0.1660, -0.3626, -0.5337,  0.5549, -0.2131,
          -0.0379, -0.4379,  0.5604,  0.2897,  0.0483, -0.4647,  0.0018,  0.7074,
          -0.6724,  0.5088,  0.0634, -0.7017, -0.1423,  0.3062,  0.6490,  0.7810,
           0.0617,  0.3941, -0.3137,  0.1339, -0.0703, -0.3644,  0.4627,  0.1115,
           0.5387,  0.4555,  0.2190, -0.5839, -0.2610,  0.1268,  0.6321,  0.8428,
           0.1171, -0.3356,  0.3763,  0.1014,  0.2303, -0.3542, -0.5363, -0.5621,
           0.5743, -0.1235, -0.0975, -0.0985, -0.5104,  0.1971,  0.0292,  0.5176],
         [ 0.7699,  0.5358, -0.0132, -0.2759, -0.2838, -0.1431, -0.2067, -0.0237,
           0.8136, -0.8335,  0.8621, -0.5405,  0.5012, -0.4703,  0.2243, -0.0733,
           0.2478,  0.4568, -0.5935,  0.5957,  0.5987,  0.5975,  0.6345, -0.1228,
          -0.0977,  0.6715, -0.8179, -0.9720, -0.4434, -0.3976, -0.0745,  0.4986,
          -0.6536, -0.0414, -0.1767, -0.5906, -0.1581,  0.2314,  0.7120,  0.5738,
          -0.4300,  0.6741, -0.7447,  0.4953, -0.5379,  0.1585,  0.6527, -0.6427,
          -0.5391,  0.6004,  0.3933,  0.1891,  0.1990,  0.3442, -0.1504,  0.4177,
           0.9318, -0.6111,  0.8700, -0.1458, -0.6190, -0.6628,  0.5561, -0.6935],
         [ 0.0131,  0.0629,  0.3803,  0.2764,  0.4189,  0.1550,  0.3154, -0.3643,
          -0.2471,  0.2233, -0.2388,  0.6338,  0.3162,  0.0977, -0.4944, -0.3711,
           0.0679,  0.8198,  0.1435,  0.3552, -0.4167,  0.4976, -0.3688,  0.4883,
           0.3098, -0.8343, -0.3056, -0.3460,  0.0569,  0.1806,  0.0290, -0.5326,
          -0.6011,  0.4761,  0.0086, -0.5862, -0.5261, -0.4653, -0.1783,  0.5851,
          -0.5900,  0.2407,  0.4660,  0.1083,  0.5366, -0.5914, -0.1915, -0.3776,
          -0.6021,  0.0995, -0.3492,  0.0112,  0.3215, -0.7538, -0.3722,  0.6638,
           0.5287, -0.5102, -0.2831,  0.5361, -0.8350, -0.4259,  0.5332,  0.6232],
         [ 0.2863,  0.3489, -0.4392, -0.8133,  0.3122,  0.1373, -0.4744,  0.1072,
          -0.0772, -0.4259,  0.4514, -0.2672,  0.4773, -0.4254, -0.3703, -0.3483,
          -0.4599,  0.6139, -0.6663, -0.2574,  0.7342,  0.4812,  0.3211,  0.5776,
           0.1343,  0.1244,  0.5100, -0.2827, -0.3017,  0.0683, -0.3691,  0.2566,
           0.5941, -0.3931, -0.4448,  0.1996,  0.4849,  0.2017, -0.4252,  0.8207,
           0.2276,  0.3202, -0.4792, -0.1392,  0.6050,  0.2625,  0.7709, -0.6595,
          -0.3650, -0.4938, -0.2378,  0.8424, -0.6583, -0.0064,  0.2966, -0.0913,
           0.5524,  0.2126,  0.5224, -0.6856, -0.6342,  0.0273, -0.3463,  0.3917],
         [ 0.0221,  0.1644,  0.8328, -0.0712, -0.4637, -0.3213,  0.6842, -0.1420,
           0.1417, -0.3198, -0.0433,  0.2753,  0.4019,  0.2900, -0.6085,  0.8301,
          -0.5873, -0.2836,  0.2723,  0.3653, -0.8446, -0.6862,  0.5976, -0.0952,
           0.7104,  0.1586, -0.5143,  0.0104, -0.6031,  0.6582,  0.0717,  0.5152,
          -0.2406, -0.4547, -0.4739,  0.1914, -0.2357, -0.7609,  0.5851,  0.8238,
          -0.0125,  0.5068, -0.3145,  0.5990, -0.5666, -0.7255,  0.5987, -0.4932,
          -0.2246, -0.1787,  0.4281,  0.2396,  0.0634, -0.5215,  0.6998,  0.4670,
          -0.4140,  0.7483,  0.6057,  0.4112, -0.3236,  0.4643,  0.7007,  0.0851],
         [-0.1529,  0.8244,  0.1060,  0.1901,  0.7888, -0.7220,  0.0244,  0.2847,
          -0.5230,  0.0029,  0.5762,  0.0560,  0.3088, -0.8512, -0.2704, -0.7346,
          -0.7477, -0.8828,  0.7125,  0.4292,  0.0094, -0.3109,  0.4585,  0.5325,
          -0.6674, -0.3158, -0.1142, -0.0696,  0.4280,  0.6806,  0.5314, -0.0975,
           0.7621,  0.7035, -0.7138, -0.0946,  0.4745,  0.3055,  0.1380, -0.3969,
           0.5363, -0.8238,  0.6377, -0.3301,  0.6226, -0.4041,  0.8127,  0.2988,
           0.4633,  0.1535, -0.5371,  0.4771,  0.6462, -0.5255,  0.3347, -0.9260,
           0.4416, -0.1366, -0.0311, -0.5141, -0.2013,  0.7225,  0.5991,  0.7533]],
        grad_fn=<SqueezeBackward1>),
 tensor([[-0.1529,  0.8244,  0.1060,  0.1901,  0.7888, -0.7220,  0.0244,  0.2847,
          -0.5230,  0.0029,  0.5762,  0.0560,  0.3088, -0.8512, -0.2704, -0.7346,
          -0.7477, -0.8828,  0.7125,  0.4292,  0.0094, -0.3109,  0.4585,  0.5325,
          -0.6674, -0.3158, -0.1142, -0.0696,  0.4280,  0.6806,  0.5314, -0.0975,
           0.7621,  0.7035, -0.7138, -0.0946,  0.4745,  0.3055,  0.1380, -0.3969,
           0.5363, -0.8238,  0.6377, -0.3301,  0.6226, -0.4041,  0.8127,  0.2988,
           0.4633,  0.1535, -0.5371,  0.4771,  0.6462, -0.5255,  0.3347, -0.9260,
           0.4416, -0.1366, -0.0311, -0.5141, -0.2013,  0.7225,  0.5991,  0.7533]],
        grad_fn=<SqueezeBackward1>))

In [ ]:
# Rnn Hidden Stats
y(a)[0]  # hidden output wrt to timestamp

tensor([[ 0.1108,  0.4846,  0.1447, -0.2413, -0.4205, -0.4411,  0.4958,  0.1356,
          0.3548, -0.5753, -0.2816, -0.1660, -0.3626, -0.5337,  0.5549, -0.2131,
         -0.0379, -0.4379,  0.5604,  0.2897,  0.0483, -0.4647,  0.0018,  0.7074,
         -0.6724,  0.5088,  0.0634, -0.7017, -0.1423,  0.3062,  0.6490,  0.7810,
          0.0617,  0.3941, -0.3137,  0.1339, -0.0703, -0.3644,  0.4627,  0.1115,
          0.5387,  0.4555,  0.2190, -0.5839, -0.2610,  0.1268,  0.6321,  0.8428,
          0.1171, -0.3356,  0.3763,  0.1014,  0.2303, -0.3542, -0.5363, -0.5621,
          0.5743, -0.1235, -0.0975, -0.0985, -0.5104,  0.1971,  0.0292,  0.5176],
        [ 0.7699,  0.5358, -0.0132, -0.2759, -0.2838, -0.1431, -0.2067, -0.0237,
          0.8136, -0.8335,  0.8621, -0.5405,  0.5012, -0.4703,  0.2243, -0.0733,
          0.2478,  0.4568, -0.5935,  0.5957,  0.5987,  0.5975,  0.6345, -0.1228,
         -0.0977,  0.6715, -0.8179, -0.9720, -0.4434, -0.3976, -0.0745,  0.4986,
         -0.6536, -0.0414, -0.1767, -0.5906, -0.1581,  0.2314,  0.7120,  0.5738,
         -0.4300,  0.6741, -0.7447,  0.4953, -0.5379,  0.1585,  0.6527, -0.6427,
         -0.5391,  0.6004,  0.3933,  0.1891,  0.1990,  0.3442, -0.1504,  0.4177,
          0.9318, -0.6111,  0.8700, -0.1458, -0.6190, -0.6628,  0.5561, -0.6935],
        [ 0.0131,  0.0629,  0.3803,  0.2764,  0.4189,  0.1550,  0.3154, -0.3643,
         -0.2471,  0.2233, -0.2388,  0.6338,  0.3162,  0.0977, -0.4944, -0.3711,
          0.0679,  0.8198,  0.1435,  0.3552, -0.4167,  0.4976, -0.3688,  0.4883,
          0.3098, -0.8343, -0.3056, -0.3460,  0.0569,  0.1806,  0.0290, -0.5326,
         -0.6011,  0.4761,  0.0086, -0.5862, -0.5261, -0.4653, -0.1783,  0.5851,
         -0.5900,  0.2407,  0.4660,  0.1083,  0.5366, -0.5914, -0.1915, -0.3776,
         -0.6021,  0.0995, -0.3492,  0.0112,  0.3215, -0.7538, -0.3722,  0.6638,
          0.5287, -0.5102, -0.2831,  0.5361, -0.8350, -0.4259,  0.5332,  0.6232],
        [ 0.2863,  0.3489, -0.4392, -0.8133,  0.3122,  0.1373, -0.4744,  0.1072,
         -0.0772, -0.4259,  0.4514, -0.2672,  0.4773, -0.4254, -0.3703, -0.3483,
         -0.4599,  0.6139, -0.6663, -0.2574,  0.7342,  0.4812,  0.3211,  0.5776,
          0.1343,  0.1244,  0.5100, -0.2827, -0.3017,  0.0683, -0.3691,  0.2566,
          0.5941, -0.3931, -0.4448,  0.1996,  0.4849,  0.2017, -0.4252,  0.8207,
          0.2276,  0.3202, -0.4792, -0.1392,  0.6050,  0.2625,  0.7709, -0.6595,
         -0.3650, -0.4938, -0.2378,  0.8424, -0.6583, -0.0064,  0.2966, -0.0913,
          0.5524,  0.2126,  0.5224, -0.6856, -0.6342,  0.0273, -0.3463,  0.3917],
        [ 0.0221,  0.1644,  0.8328, -0.0712, -0.4637, -0.3213,  0.6842, -0.1420,
          0.1417, -0.3198, -0.0433,  0.2753,  0.4019,  0.2900, -0.6085,  0.8301,
         -0.5873, -0.2836,  0.2723,  0.3653, -0.8446, -0.6862,  0.5976, -0.0952,
          0.7104,  0.1586, -0.5143,  0.0104, -0.6031,  0.6582,  0.0717,  0.5152,
         -0.2406, -0.4547, -0.4739,  0.1914, -0.2357, -0.7609,  0.5851,  0.8238,
         -0.0125,  0.5068, -0.3145,  0.5990, -0.5666, -0.7255,  0.5987, -0.4932,
         -0.2246, -0.1787,  0.4281,  0.2396,  0.0634, -0.5215,  0.6998,  0.4670,
         -0.4140,  0.7483,  0.6057,  0.4112, -0.3236,  0.4643,  0.7007,  0.0851],
        [-0.1529,  0.8244,  0.1060,  0.1901,  0.7888, -0.7220,  0.0244,  0.2847,
         -0.5230,  0.0029,  0.5762,  0.0560,  0.3088, -0.8512, -0.2704, -0.7346,
         -0.7477, -0.8828,  0.7125,  0.4292,  0.0094, -0.3109,  0.4585,  0.5325,
         -0.6674, -0.3158, -0.1142, -0.0696,  0.4280,  0.6806,  0.5314, -0.0975,
          0.7621,  0.7035, -0.7138, -0.0946,  0.4745,  0.3055,  0.1380, -0.3969,
          0.5363, -0.8238,  0.6377, -0.3301,  0.6226, -0.4041,  0.8127,  0.2988,
          0.4633,  0.1535, -0.5371,  0.4771,  0.6462, -0.5255,  0.3347, -0.9260,
          0.4416, -0.1366, -0.0311, -0.5141, -0.2013,  0.7225,  0.5991,  0.7533]],
       grad_fn=<SqueezeBackward1>)

In [ ]:
b= y(a)[1]  # final output
b

tensor([[-0.1529,  0.8244,  0.1060,  0.1901,  0.7888, -0.7220,  0.0244,  0.2847,
         -0.5230,  0.0029,  0.5762,  0.0560,  0.3088, -0.8512, -0.2704, -0.7346,
         -0.7477, -0.8828,  0.7125,  0.4292,  0.0094, -0.3109,  0.4585,  0.5325,
         -0.6674, -0.3158, -0.1142, -0.0696,  0.4280,  0.6806,  0.5314, -0.0975,
          0.7621,  0.7035, -0.7138, -0.0946,  0.4745,  0.3055,  0.1380, -0.3969,
          0.5363, -0.8238,  0.6377, -0.3301,  0.6226, -0.4041,  0.8127,  0.2988,
          0.4633,  0.1535, -0.5371,  0.4771,  0.6462, -0.5255,  0.3347, -0.9260,
          0.4416, -0.1366, -0.0311, -0.5141, -0.2013,  0.7225,  0.5991,  0.7533]],
       grad_fn=<SqueezeBackward1>)

In [ ]:
z= nn.Linear(64,326)
z

Linear(in_features=64, out_features=326, bias=True)

In [ ]:
z(b)

tensor([[ 1.1775e-01, -2.9113e-01, -2.2815e-01,  1.6919e-01, -1.0926e-01,
         -1.9259e-01, -1.1151e-01,  2.1053e-01,  1.6097e-01, -4.0086e-01,
         -2.3235e-02,  3.4714e-01, -1.9931e-01, -6.4126e-02,  3.0785e-01,
         -3.3484e-01,  2.3484e-01,  2.1193e-01, -8.4577e-02, -4.1982e-02,
         -1.1275e-02, -2.8693e-03, -1.1274e-01,  6.1854e-02, -4.2460e-01,
          6.3924e-04, -3.3299e-01,  2.5712e-01, -1.1244e-01,  1.6047e-02,
         -4.3801e-01,  3.4009e-02,  4.1259e-01, -1.5946e-01, -6.1794e-01,
          9.9170e-02, -3.1646e-01, -3.2908e-02, -6.3333e-01,  4.0247e-02,
          1.3192e-01, -2.7440e-01,  3.8574e-01, -2.9847e-02, -8.7932e-03,
          3.9193e-01, -2.6665e-01, -1.5180e-01, -9.6261e-02,  3.1084e-02,
          2.8964e-01,  6.9228e-02,  8.4083e-02, -5.4726e-01, -3.0873e-01,
          4.5294e-02,  1.7652e-02, -3.7573e-02, -2.3478e-01, -6.6994e-02,
         -7.7291e-02, -2.6233e-02,  8.2624e-02,  3.4272e-01,  5.4276e-01,
          2.7205e-01, -2.6149e-01, -1.4756e-01, -4.6669e-01,  2.7306e-01,
          1.8705e-01,  3.0007e-01,  2.6413e-01, -5.3457e-01, -2.2907e-01,
         -4.6245e-01, -1.7432e-01,  4.2550e-02,  5.2975e-03,  1.0116e-01,
          1.0985e-01, -3.9040e-01, -1.3612e-01,  1.0686e-01, -1.9608e-01,
         -1.4469e-01,  6.0358e-01,  1.3965e-02, -2.2070e-01, -2.1158e-01,
          6.7985e-01, -5.0189e-01, -2.0299e-01, -8.3579e-02,  1.4701e-01,
         -2.7775e-01, -1.7672e-01, -3.7297e-01, -5.3925e-01, -4.4436e-01,
          1.4899e-01,  5.5057e-01,  6.0866e-02,  5.2144e-02, -1.8453e-03,
          7.5401e-02,  2.3955e-01, -1.2906e-01, -3.9107e-01,  6.5469e-01,
         -1.2570e-01, -2.5769e-01,  3.1062e-03, -7.3553e-02, -2.1292e-01,
          1.4272e-01, -6.9978e-01, -8.0421e-01, -9.2583e-02, -7.8975e-02,
         -2.1819e-01,  2.4688e-01, -3.2376e-02,  1.7368e-01, -2.0780e-01,
          4.8686e-01, -3.2875e-01,  2.7223e-01,  1.3928e-01,  2.9604e-01,
          1.3158e-01, -1.8300e-01, -1.8673e-01,  3.0589e-02, -9.7879e-02,
         -4.0085e-01,  2.5677e-01,  3.5671e-01,  5.3609e-01,  5.1181e-01,
          6.6186e-01, -6.2501e-01,  3.4517e-01, -2.3768e-01,  2.2648e-01,
          6.2621e-01,  4.9108e-02, -3.4621e-02,  4.3321e-01, -8.7765e-02,
          3.3793e-01, -3.5816e-02, -2.2932e-01,  5.0944e-02,  3.1466e-01,
         -4.0106e-01, -3.0904e-01, -7.5216e-02, -3.0059e-01,  4.2209e-01,
         -1.1701e-01,  2.1867e-01,  5.1784e-01, -6.8084e-02,  9.9604e-02,
         -5.7518e-01, -8.3247e-02,  5.7298e-01, -3.2036e-01, -2.4864e-01,
          9.7952e-02, -5.0265e-02, -5.7386e-01, -4.3107e-01, -1.6978e-01,
          4.2184e-01,  1.3582e-01, -3.1567e-01,  1.4915e-01, -6.2145e-01,
          3.9931e-01,  5.0594e-02,  1.4266e-01,  3.5594e-03,  9.3845e-02,
          2.5588e-01, -9.4804e-02,  4.7398e-02, -4.5242e-01, -4.4122e-01,
         -1.7574e-01, -5.4620e-01,  7.3195e-02, -3.1227e-02, -5.7286e-02,
          3.4564e-01, -2.5437e-01,  2.2719e-01, -2.8178e-01,  1.1187e-01,
          1.0136e-01, -6.4493e-01, -2.5251e-01,  5.6151e-01, -3.1923e-01,
         -5.8599e-01,  1.6967e-01, -2.2530e-01, -8.6934e-02,  2.0617e-01,
          3.4620e-01,  5.3442e-01, -8.1951e-02, -1.6783e-01,  6.8251e-02,
         -7.4121e-02,  1.8750e-01, -1.5206e-01,  3.6295e-01,  1.9991e-01,
          1.5418e-01,  2.5171e-01, -9.4617e-02,  2.0504e-01,  1.7603e-01,
         -3.0609e-01,  1.1641e-01,  1.9868e-01, -1.6902e-01,  2.5454e-02,
          3.5587e-01, -2.3124e-01,  6.1474e-01, -5.7886e-01,  3.0873e-01,
          4.9950e-02,  2.9545e-01, -4.7849e-01, -2.1151e-01, -1.5171e-01,
          1.1673e-01, -3.4461e-01, -2.0029e-01,  5.2264e-02,  3.8938e-02,
         -4.7442e-01, -9.1102e-01, -1.6240e-01,  9.2160e-02,  3.6951e-01,
          3.4913e-01, -3.7192e-01, -3.0168e-01,  2.7394e-01,  1.6408e-01,
          1.4036e-01, -4.8413e-01, -3.1613e-01, -6.9146e-02,  1.7165e-01,
          5.0232e-01,  3.2012e-01,  2.0827e-02,  2.7820e-01,  8.8112e-01,
         -4.5658e-01, -1.4636e-01, -1.1255e-01,  3.5582e-03,  4.4452e-02,
          1.8254e-01,  6.5984e-02, -1.7794e-01,  1.3308e-01, -1.2177e-01,
          8.2491e-01, -2.7917e-01,  2.3340e-01, -3.1312e-01, -4.5892e-01,
          5.0156e-01,  5.8073e-02,  2.2118e-02,  4.2267e-01,  2.0845e-01,
         -2.3066e-01,  6.1226e-01,  2.4059e-01,  9.0198e-02, -3.3433e-01,
          1.5721e-02, -2.9656e-02, -1.5418e-01,  2.6030e-01,  2.8634e-01,
          1.5261e-01, -2.4659e-01,  5.4929e-01, -1.0067e-01,  9.4964e-02,
          1.3419e-01,  2.0837e-01, -4.5500e-01,  1.4793e-01,  3.2179e-02,
          5.3787e-01,  5.3306e-02,  8.2122e-02, -2.3852e-01, -4.3871e-04,
         -6.4660e-02, -7.7089e-01,  2.4568e-02,  4.7262e-01, -1.0786e-01,
         -1.3571e-01,  3.6207e-01,  1.8586e-01, -4.4448e-02, -5.5505e-01,
          2.4771e-01, -2.3251e-03,  4.2849e-02,  8.4291e-02, -9.5706e-02,
         -3.8053e-02]], grad_fn=<AddmmBackward0>)

In [ ]:
z(b).shape

torch.Size([1, 326])

In [ ]:
learning_rate= 0.001
epochs=20

In [ ]:
model= SimpleRNN(len(vocab))

In [ ]:
criterion= nn.CrossEntropyLoss()
optimizer= torch.optim.Adam(model.parameters(),lr=learning_rate)

In [ ]:
# Training loop
for epoch in range(epochs):
  total_loss=0
  for question,answer in dataloader:
    optimizer.zero_grad()

    # forward pass
    output= model(question)
    # calculate loss
    loss= criterion(output,answer[0])
    # gradients
    loss.backward()
    #update
    optimizer.step()
    # calculate total loss
    total_loss= total_loss + loss.item()

  print(f"Epoch: {epoch +1}, Loss:{total_loss:4f}")

Epoch: 1, Loss:518.866976
Epoch: 2, Loss:450.721770
Epoch: 3, Loss:372.662608
Epoch: 4, Loss:310.417091
Epoch: 5, Loss:256.967411
Epoch: 6, Loss:208.579506
Epoch: 7, Loss:164.292683
Epoch: 8, Loss:126.752439
Epoch: 9, Loss:97.035410
Epoch: 10, Loss:73.589808
Epoch: 11, Loss:56.917022
Epoch: 12, Loss:43.817918
Epoch: 13, Loss:34.805841
Epoch: 14, Loss:28.051549
Epoch: 15, Loss:22.690211
Epoch: 16, Loss:19.023220
Epoch: 17, Loss:15.888299
Epoch: 18, Loss:13.485676
Epoch: 19, Loss:11.638974
Epoch: 20, Loss:10.116184

In [ ]:
# Prediction
def predict(model,question, threshold=0.5):
  # convert text into convet
 numerical_question= text_to_indices(question,vocab)
# print(numerical_question)

 # convert numerical to tensor
 question_tensor= torch.tensor(numerical_question).unsqueeze(0)
# print(question_tensor)

 # forward pass to model
 output= model(question_tensor)
 #print(output)

 # convert logits to probability
 probs= torch.nn.functional.softmax(output, dim=1)
 # find index of max probs
 value, index= torch.max(probs, dim=1)
 if value < threshold:
   print("I dont know")
 else:
  print(list(vocab.keys())[index])
 #print(value, index)

In [ ]:
predict(model,"what is prince")

I dont know

In [ ]:
list(vocab.keys())[16]

'harper-lee'

In [ ]:
predict(model,"what is the capital of France")

paris

In [ ]:
list(vocab.keys())[7]

'paris'

In [ ]:
predict(model,"what is the capital of France")

paris